name: main

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck

      - name: Running tests
        run: ./test/shellcheck.sh
